steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/teseobot-487515/crm-agentico-compiler', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/teseobot-487515/crm-agentico-compiler']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'crm-agentico-compiler'
  - '--image'
  - 'gcr.io/teseobot-487515/crm-agentico-compiler'
  - '--region'
  - 'us-central1'
images:
- 'gcr.io/teseobot-487515/crm-agentico-compiler'
options:
  logging: CLOUD_LOGGING_ONLY
