substitutions:
  _REGION: us-central1
  _IMAGE_REPO: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/teseo-context-repo/context-kdb-compiler

steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '-t'
  - '${_IMAGE_REPO}:${COMMIT_SHA}'
  - '-t'
  - '${_IMAGE_REPO}:latest'
  - '.'

- id: push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_IMAGE_REPO}']

- id: deploy
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'context-kdb-compiler'
    - '--image'
    - '${_IMAGE_REPO}:${COMMIT_SHA}'
    - '--region'
    - '${_REGION}'
  waitFor: ['push']

images:
- '${_IMAGE_REPO}:${COMMIT_SHA}'
- '${_IMAGE_REPO}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
