-- DEPRECATED: Este archivo se mantiene solo como referencia histórica.
-- El esquema canónico del Cold-Tier vive en: context-kdb-compiler/migrations/001_init.sql
-- No ejecutar este archivo directamente. Usar las migraciones versionadas.
--
-- Para aplicar migraciones:
--   psql $DATABASE_URL -f migrations/001_init.sql
